// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXRropwVcwMANib13iPfwF_yhiALejR58',
    appId: '1:1030338500463:web:20ca4c9529a6d1107e7a9a',
    messagingSenderId: '1030338500463',
    projectId: 'esp32-test-8eea4',
    authDomain: 'esp32-test-8eea4.firebaseapp.com',
    databaseURL: 'https://esp32-test-8eea4-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-test-8eea4.appspot.com',
    measurementId: 'G-MS6R5BJWMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7hnTQ0AbkUF23p2nikoH6M7Fih7auatA',
    appId: '1:1030338500463:android:017df292fea396377e7a9a',
    messagingSenderId: '1030338500463',
    projectId: 'esp32-test-8eea4',
    databaseURL: 'https://esp32-test-8eea4-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-test-8eea4.appspot.com',
  );
}
